M: 4
context_aspect_ratio: 1
context_scale: !!python/tuple
- 0.85
- 1.0
decoder_depth: 6
embed_dim: 64
enc_depth: 8
enc_heads: 8
img_size: 224
in_chans: 3
lr: 0.001
m: 0.996
m_start_end: !!python/tuple
- 0.996
- 1.0
patch_size: 16
target_aspect_ratio: !!python/tuple
- 0.75
- 1.5
target_scale: !!python/tuple
- 0.15
- 0.2
weight_decay: 0.05
